### ISSUE TITLE
大佬，能不能加入注意力机制

### ISSUE THREAD

**Issue by machulong** [KittenCN/predict_Lottery_ticket#1]
大佬，能不能加入注意力机制

**Comment by KittenCN** [comment]
我目前重点是向pytorch迁移，因为Tensorflow实在不是我的强项，之后会调整模型和业务逻辑的

**Comment by KittenCN** [comment]
已经开始基于transformer开发了，期待志同道合者一起coding
https://github.com/KittenCN/predict_Lottery_ticket_pytorch
