### ISSUE TITLE
博主，你好，根据安装提示并未安装tensorflow，这是什么问题？

### ISSUE THREAD

**Issue by nottellyou** [KittenCN/predict_Lottery_ticket#12]
OS：win7_x64
python : 3.8.17

![snipaste20230803_170351](https://github.com/KittenCN/predict_Lottery_ticket/assets/8598743/345400db-26d8-4134-8a37-90b159185a6d)

![snipaste20230803_160807](https://github.com/KittenCN/predict_Lottery_ticket/assets/8598743/f088be0b-2639-4b89-8ba6-499ec819bf5c)

(py38) D:\Lottery\predict_Lottery_ticket-main>
(py38) D:\Lottery\predict_Lottery_ticket-main>python get_data.py --name ssq
Traceback (most recent call last):
  File "get_data.py", line 7, in <module>
    from common import get_data_run
  File "D:\Lottery\predict_Lottery_ticket-main\common.py", line 13, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

(py38) D:\Lottery\predict_Lottery_ticket-main>pip3 show tensorflow
WARNING: Package(s) not found: tensorflow

**Comment by nottellyou** [comment]
希望博主能指点小弟一二。
在此谢过

**Comment by KittenCN** [comment]
那就再conda里面安装一下适合的tensorflow
