### ISSUE TITLE
感觉需要改进的地方

### ISSUE THREAD

**Issue by ldc-yy** [KittenCN/predict_Lottery_ticket#13]
1：数据源，现在的数据源登录不上，建议使用17500，这么多年了还是很稳定的
2：预测结果，现在预测结果就是最新的一期，可以把历史预测也打印出来吗？比如说最近50期或者100期的预测结果【整个参数，动态设定】，最好是开奖结果和预测结果一起，这样能明显的看出来之前的预测的准确性
3：预测结果的数量，也整个动态的吧，比如说，每期预测5注号，10注号

未完待续，持续交流

**Comment by KittenCN** [comment]
1. 数据源能正常使用
2. 这个就手工去对比吧，我主要还是考虑算法的部分，易用性暂时不考虑
3. 预测的结果是按概率分布展现的，当你要多组结果的时候，会有一些问题。
