### ISSUE TITLE
快乐8提升中奖率建议

### ISSUE THREAD

**Issue by 359886056** [KittenCN/predict_Lottery_ticket#14]
### kl8_anylysis
1. 选10中奖率太低，建议改成中奖率最高的选4、选5，如果追求稍微高点的奖金可以选7
2. matplotlib 聚类图和原项目numpy版本冲突，建议删除这个代码即可
3. 选号方法，只要热号(近10-20期出现较多的号码)、跳号、邻号、斜连号等
不知是否可以建立个qq群以便更好的讨论细节

**Comment by KittenCN** [comment]
kl8_anylysis只是我用来尝试从统计学角度寻找可能规律的测试程序，并没有考虑由其产生号码。

**Comment by KittenCN** [comment]
这里有discussion，可以直接讨论
