### ISSUE TITLE
大佬好，在run_train_model.py时遇到问题啦？help ！

### ISSUE THREAD

**Issue by Zongning24** [KittenCN/predict_Lottery_ticket#15]
This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "D:\Files\python object\predict_Lottery_ticket-main2\run_train_model.py", line 17, in <module>
    from modeling import LstmWithCRFModel, SignalLstmModel, tf
  File "D:\Files\python object\predict_Lottery_ticket-main2\modeling.py", line 8, in <module>
    from tensorflow_addons.text.crf import crf_decode, crf_log_likelihood
ModuleNotFoundError: No module named 'tensorflow_addons'

**Comment by KittenCN** [comment]
These are errors because Tensorflow and tensorflow_addons are not installed, or are installed in an incorrect version.
