### ISSUE TITLE
关于库和python版本问题

### ISSUE THREAD

**Issue by laydownfish** [KittenCN/predict_Lottery_ticket#19]
请问一定要用python3.8系统和tensflow2.3版本吗？如果用其他版本有哪些差距吗？主要是我的系统没法装ancode，在notebook上只支持python3.9，tensflow也只有2.13.版本，请问影响大吗？

**Comment by KittenCN** [comment]
我只是推荐这几个版本，因为这几个我测试过，其他的，我不能保证正常使用。
