### ISSUE TITLE
大佬好 我想问一下 关于每轮训练数量的问题

### ISSUE THREAD

**Issue by WolfEllobo** [KittenCN/predict_Lottery_ticket#26]
大佬好，我想问一下，篮球或者红球训练次数多了以后，每轮训练数量不拉高就会很慢，我吧每轮训的练数量拉高之后，训练完以后是不能直接预测的，我还要吧每轮训的练数量设置成1，这样是不是吧我第一次的覆盖了。我用--predict_pro 1，或者吧蓝红球的训练次数拉低以后再训练，文件都会缩小...

我的指令是这样用的，是否有错。
第一种
1. python run_train_model.py --name ssq  --windows_size 3,5,7 --red_epochs 128 --blue_epochs 128 --batch_size 24
2. python run_train_model.py --name ssq  --windows_size 3,5,7 --predict_pro 1
第二种
1. python run_train_model.py --name ssq  --windows_size 3,5,7 --red_epochs 128 --blue_epochs 128 --batch_size 24
2. python run_train_model.py --name ssq  --windows_size 3,5,7 --red_epochs 128 --blue_epochs 128 --batch_size 24 --predict_pro 1
上面两种是正确的吗，不知道有没有办法解决这个问题

**Comment by KittenCN** [comment]
--predict_pro 1 只是将红球篮球的epchs，以及batchsize强行定为1，以方便训练出来的模型能被预测代码正确识别，原理上讲，不会对原来的模型有很大的结果变化，但是确实又肯定有不同。文件变小是一定的，因为参数量大大下降了。
如果很关注这种结果的变化，可以训练的时候就用batchsize 1来训练，就不需要 --predict_pro 1的操作了
