### ISSUE TITLE
请问kl8的训练和预测命令

### ISSUE THREAD

**Issue by AEDELSTAN** [KittenCN/predict_Lottery_ticket#30]
如题，抱歉我是小白不太懂
python run_train_model.py --name kl8
python run_predict.py  --name kl8
是不是这样就可以了

还有就是我训练了两次，预测号码会有些许不同。请问这个训练是会迭代的还是每次训练都是从头开始的呀

**Comment by AEDELSTAN** [comment]
再请教一下，我把requirements的所有包都下载了，如果我想切换gpu训练应该使用什么命令
感谢

**Comment by KittenCN** [comment]
windows_size就是说，用前几期的数据，来预测当前期。训练次数就看个人的理解了，任意的正整数都可以
