### ISSUE TITLE
大佬想咨询下 每次新增数据后 都需要重新训练模型 再预测吗

### ISSUE THREAD

**Issue by lxxxxxxk** [KittenCN/predict_Lottery_ticket#35]
想模拟一些数据 都是要先python run_train_model.py --name ssq  --windows_size 3,5,7 --red_epochs 1 --blue_epochs 1 --batch_size 1  #
再python run_predict.py  --name ssq --windows_size 3,5,7  吗 感谢大佬

**Comment by KittenCN** [comment]
神经网络的原理上是不用重新训练，但是这个前提是你认为当前一期的数字也是符合前面模型的；如果你觉得每次的数字都是新的模型，就应该重新训练。。看个人的理解了。
