### ISSUE TITLE
快乐8预测了20个号

### ISSUE THREAD

**Issue by Jupiter-sun** [KittenCN/predict_Lottery_ticket#38]
大佬，快乐8预测了20个号，但是从这20个号中选几个号的组合也太多了，能否推荐十个号

**Comment by KittenCN** [comment]
因为出奖是出20个号，所以我默认的输出维度也是20个

**Comment by Jupiter-sun** [comment]
是的，但是从20个号中选几个号也是很难的

**Comment by Jupiter-sun** [comment]
修改config的输出数量可以吗

**Comment by KittenCN** [comment]
config的输出是要对应输入的维度的，所以不能改,除非，再新建一个新的快乐8模式，历史数据就是10位的，但是这样又有新问题，要取哪10位。。因为哪怕是对于彩票本身而言，那20位都是正确的，所以预测也是20位。只有输出完这20位后，再用别的方法进行筛选，比如统计学，概率学等等

**Comment by Jupiter-sun** [comment]
明白 大佬
