### ISSUE TITLE
小小的建议，望作者大佬有空看一下，万分感谢

### ISSUE THREAD

**Issue by B0luo** [KittenCN/predict_Lottery_ticket#5]
1、能不能自定义训练数据，有两点考量：①体彩摇奖机器从2019年12月有换新 ②想用最新一期已开奖号，对比调试合适的参数
2、config配置文件修改pls的轮数和每轮训练量貌似不生效，还是得执行的时候设置参数才行
3、高于1个batch_size训练后还得执行一遍才能预测，对于算力配置低的机器有点体验感差了。（心理作用，感觉用--predict_pro 1 参数会影响预测结果）

**Comment by KittenCN** [comment]
1. 要自定义数据，改动有点大，但是确实可以做到
2. 配置文件和执行参数是冲突的，以执行参数为主，这是我自己调试方便，之后会给执行参数加上开关
3. batch size 是个很麻烦的问题，因为batch size直接关系到网络模型的层数，所以我把它存到模型字典里面了，那么这就要求训练和预测时参数一致才行，某种意义上，使用了predict pro参数，是一定会影响结果的，所以最好是全部用1个batch去训练和预测，当然，我也纠结过要不要改模型，来适应多batch size

**Comment by B0luo** [comment]
感谢大佬回复，了解了，目前用起来还是很不错的。已看到更新，执行力太强了！🐮啊

**Comment by teddyztd** [comment]
大佬 请问运行 python run_train_model.py --name ssq 显示 ModuleNotFoundError: No module named 'tensorflow_addons' 错误再
modeling.py 里 不满足软件包要求'tensorflow-addons==0.13. 请问如何解决谢谢

**Comment by KittenCN** [comment]
> 大佬 请问运行 python run_train_model.py --name ssq 显示 ModuleNotFoundError: No module named 'tensorflow_addons' 错误再 modeling.py 里 不满足软件包要求'tensorflow-addons==0.13. 请问如何解决谢谢
建议按照requirements.txt里面的版本要求安装，特别是'tensorflow-addons这种，是与tensorflow的版本有关联的，不能随便安装

**Comment by KittenCN** [comment]
> 大佬 请问运行 python run_train_model.py --name ssq 显示 ModuleNotFoundError: No module named 'tensorflow_addons' 错误再 modeling.py 里 不满足软件包要求'tensorflow-addons==0.13. 请问如何解决谢谢

建议按照requirements.txt里面的版本要求安装，特别是'tensorflow-addons这种，是与tensorflow的版本有关联的，不能随便安装

**Comment by teddyztd** [comment]
> > 大佬 请问运行 python run_train_model.py --name ssq 显示 ModuleNotFoundError: No module named 'tensorflow_addons' 错误再 modeling.py 里 不满足软件包要求'tensorflow-addons==0.13. 请问如何解决谢谢
> 
> 建议按照requirements.txt里面的版本要求安装，特别是'tensorflow-addons这种，是与tensorflow的版本有关联的，不能随便安装

谢谢大佬已经解决
